# -*- coding: utf-8 -*-
"""Copy of Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNRAsRKXoYUM4_AN01HTBoL_JrX3Vnrd
"""

# FIND-S Algorithm Implementation

def find_s(training_data):
    """
    training_data: list of tuples (attributes_list, target)
    target is 'Yes' or 'No'
    """

    # Step 1: Initialize hypothesis with most specific values
    hypothesis = ['Ø'] * len(training_data[0][0])

    # Step 2: Process training examples
    for attributes, target in training_data:
        if target == 'Yes':  # consider only positive examples
            for i in range(len(attributes)):
                if hypothesis[i] == 'Ø':
                    hypothesis[i] = attributes[i]
                elif hypothesis[i] != attributes[i]:
                    hypothesis[i] = '?'

    return hypothesis


# Training dataset
training_data = [
    (['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same'], 'Yes'),
    (['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same'], 'Yes'),
    (['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change'], 'No'),
    (['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change'], 'Yes')
]

# Run FIND-S
final_hypothesis = find_s(training_data)

print("Most Specific Hypothesis:")
print(final_hypothesis)

