# -*- coding: utf-8 -*-
"""exp 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KuH38r5SJQOXnkIqAmQLo1fFjyN7iPv5
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

# -----------------------------------------
# 1. Load Dataset (Iris)
# -----------------------------------------

iris = load_iris()
X = iris.data
y = iris.target

# Split dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

# -----------------------------------------
# 2. Create Naïve Bayes Model
# -----------------------------------------

model = GaussianNB()

# Train the model
model.fit(X_train, y_train)

# -----------------------------------------
# 3. Make Predictions
# -----------------------------------------

y_pred = model.predict(X_test)

# -----------------------------------------
# 4. Evaluation
# -----------------------------------------

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n")
print(cm)

print("\nAccuracy:", accuracy)

# -----------------------------------------
# 5. Predict New Sample
# -----------------------------------------

new_sample = np.array([[5.1, 3.5, 1.4, 0.2]])
prediction = model.predict(new_sample)

print("\nNew Sample:", new_sample)
print("Predicted Class:", prediction[0])
print("Class Name:", iris.target_names[prediction[0]])