# -*- coding: utf-8 -*-
"""exp 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGF20mMb6XSdXJvBgJ9bg1FNZdy3vA27
"""

import numpy as np

# -----------------------------------------
# 1. Create XOR Dataset
# -----------------------------------------

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# -----------------------------------------
# 2. Activation Function (Sigmoid)
# -----------------------------------------

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# -----------------------------------------
# 3. Initialize Network Parameters
# -----------------------------------------

input_neurons = 2
hidden_neurons = 4
output_neurons = 1

np.random.seed(1)

W1 = np.random.uniform(size=(input_neurons, hidden_neurons))
b1 = np.random.uniform(size=(1, hidden_neurons))

W2 = np.random.uniform(size=(hidden_neurons, output_neurons))
b2 = np.random.uniform(size=(1, output_neurons))

learning_rate = 0.1
epochs = 10000

# -----------------------------------------
# 4. Training using Backpropagation
# -----------------------------------------

for epoch in range(epochs):

    # Forward Propagation
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    final_output = sigmoid(final_input)

    # Calculate Error
    error = y - final_output

    # Backpropagation

    # Output Layer Gradient
    d_output = error * sigmoid_derivative(final_output)

    # Hidden Layer Gradient
    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update Weights and Biases
    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

# -----------------------------------------
# 5. Testing the Trained Network
# -----------------------------------------

print("Final Output after Training:\n")
print(final_output)

# Test Prediction
print("\nPredictions:")
for i in range(len(X)):
    print(X[i], "->", round(float(final_output[i]), 3))