# -*- coding: utf-8 -*-
"""exp 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALREUyRLUSXSDTejwVlINAkSW3AYirzw
"""

import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# -----------------------------------------
# 1. Load Dataset (California Housing)
# -----------------------------------------

data = fetch_california_housing()
X = data.data
y = data.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

# -----------------------------------------
# 2. Create Linear Regression Model
# -----------------------------------------

model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# -----------------------------------------
# 3. Make Predictions
# -----------------------------------------

y_pred = model.predict(X_test)

# -----------------------------------------
# 4. Evaluation
# -----------------------------------------

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Model Coefficients:\n", model.coef_)
print("\nIntercept:\n", model.intercept_)

print("\nMean Squared Error (MSE):", mse)
print("R2 Score:", r2)

# -----------------------------------------
# 5. Predict New Sample
# -----------------------------------------

new_sample = X_test[:1]
prediction = model.predict(new_sample)

print("\nNew Sample Prediction:", prediction)
print("Actual Value:", y_test[:1])