# -*- coding: utf-8 -*-
"""exp 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eA0FLoWKiKOCwTniZrJ8VjUOd7dXgogT
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# -----------------------------------------
# 1. Generate Sample Data (2 Gaussian Clusters)
# -----------------------------------------

np.random.seed(0)
data1 = np.random.normal(loc=2, scale=0.5, size=150)
data2 = np.random.normal(loc=8, scale=0.8, size=150)

X = np.hstack((data1, data2))

# -----------------------------------------
# 2. Initialize Parameters
# -----------------------------------------

n = len(X)
k = 2  # number of clusters

means = np.random.choice(X, k)
variances = np.random.random_sample(k)
weights = np.ones(k) / k

responsibilities = np.zeros((n, k))

# -----------------------------------------
# 3. EM Algorithm
# -----------------------------------------

max_iterations = 100

for iteration in range(max_iterations):

    # -------- E-Step --------
    for i in range(k):
        responsibilities[:, i] = weights[i] * norm.pdf(X, means[i], np.sqrt(variances[i]))

    responsibilities = responsibilities / responsibilities.sum(axis=1, keepdims=True)

    # -------- M-Step --------
    for i in range(k):
        weight_sum = responsibilities[:, i].sum()

        means[i] = (responsibilities[:, i] * X).sum() / weight_sum

        variances[i] = (responsibilities[:, i] * (X - means[i])**2).sum() / weight_sum

        weights[i] = weight_sum / n

# -----------------------------------------
# 4. Results
# -----------------------------------------

print("Final Means:", means)
print("Final Variances:", variances)
print("Final Mixing Weights:", weights)

# -----------------------------------------
# 5. Plot Clustering Result
# -----------------------------------------

cluster_labels = np.argmax(responsibilities, axis=1)

plt.scatter(X, np.zeros(n), c=cluster_labels, cmap='viridis')
plt.title("EM Algorithm - Gaussian Mixture Clustering")
plt.show()