# -*- coding: utf-8 -*-
"""exp 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kr89rYJa1i8ZijzvUkvKZW9OFUQxH5g_
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from collections import Counter

# -----------------------------------------
# 1. Load Dataset (Iris Dataset)
# -----------------------------------------

iris = load_iris()
X = iris.data
y = iris.target

# Split into Training and Testing Data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

# -----------------------------------------
# 2. Define Euclidean Distance Function
# -----------------------------------------

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

# -----------------------------------------
# 3. KNN Class
# -----------------------------------------

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        predictions = [self._predict(x) for x in X]
        return np.array(predictions)

    def _predict(self, x):
        # Compute distances
        distances = [euclidean_distance(x, x_train)
                     for x_train in self.X_train]

        # Get k nearest samples
        k_indices = np.argsort(distances)[:self.k]

        # Get labels of k nearest samples
        k_labels = [self.y_train[i] for i in k_indices]

        # Majority voting
        most_common = Counter(k_labels).most_common(1)
        return most_common[0][0]

# -----------------------------------------
# 4. Train the Model
# -----------------------------------------

k = 5
knn = KNN(k=k)
knn.fit(X_train, y_train)

# -----------------------------------------
# 5. Test the Model
# -----------------------------------------

predictions = knn.predict(X_test)

# Calculate Accuracy
accuracy = np.sum(predictions == y_test) / len(y_test)

print("K value:", k)
print("Accuracy:", accuracy)

# -----------------------------------------
# 6. Predict New Sample
# -----------------------------------------

new_sample = np.array([[5.1, 3.5, 1.4, 0.2]])
prediction = knn.predict(new_sample)

print("\nNew Sample:", new_sample)
print("Predicted Class:", prediction[0])
print("Class Name:", iris.target_names[prediction[0]])