# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSQpfFdtnsSTntaPzJOMG9umHqH6nEJD
"""

import pandas as pd
from io import StringIO

# -------------------------------
# Step 1: Create the dataset
# -------------------------------
csv_data = StringIO("""
Sky,AirTemp,Humidity,Wind,Water,Forecast,EnjoySport
Sunny,Warm,Normal,Strong,Warm,Same,Yes
Sunny,Warm,High,Strong,Warm,Same,Yes
Rainy,Cold,High,Strong,Warm,Change,No
Sunny,Warm,High,Strong,Cool,Change,Yes
""")

data = pd.read_csv(csv_data)

# -------------------------------
# Step 2: Candidate Elimination
# -------------------------------
def candidate_elimination(data):
    attributes = data.iloc[:, :-1].values
    target = data.iloc[:, -1].values

    num_attr = attributes.shape[1]

    # Initialize S and G
    S = ['0'] * num_attr
    G = [['?' for _ in range(num_attr)]]

    for i in range(len(target)):

        if target[i].lower() == 'yes':  # Positive example
            for j in range(num_attr):
                if S[j] == '0':
                    S[j] = attributes[i][j]
                elif S[j] != attributes[i][j]:
                    S[j] = '?'

            # Remove inconsistent hypotheses from G
            G = [g for g in G if is_consistent(g, attributes[i])]

        else:  # Negative example
            new_G = []
            for g in G:
                for j in range(num_attr):
                    if g[j] == '?' and S[j] != attributes[i][j]:
                        new_h = g.copy()
                        new_h[j] = S[j]
                        new_G.append(new_h)

            G = remove_duplicates(new_G)

        # Display intermediate steps
        print(f"\nAfter Training Instance {i+1}:")
        print("S =", S)
        print("G =", G)

    return S, G

# -------------------------------
# Helper Functions
# -------------------------------
def is_consistent(hypothesis, instance):
    for h, i in zip(hypothesis, instance):
        if h != '?' and h != i:
            return False
    return True

def remove_duplicates(hypotheses):
    final = []
    for h in hypotheses:
        if h not in final:
            final.append(h)
    return final

# -------------------------------
# Step 3: Run Algorithm
# -------------------------------
S_final, G_final = candidate_elimination(data)

print("\n================ FINAL RESULT ================")
print("Final Specific Hypothesis (S):")
print(S_final)

print("\nFinal General Hypotheses (G):")
for g in G_final:
    print(g)